### ISSUE TITLE
ppc/aarch + updated cpu targets

### ISSUE THREAD

**Issue by ngam** [conda-forge/bazel-toolchain-feedstock#11]
### Comment:

@xhochy I have two general questions about this toolchain:
1. Is there a reason why it wouldn't work for ppc/aarch out of the gate?
2. I was trying to set up some ambitious `-march -mtune` flags through bazel but things failed with weird errors; on top of your head, is that something that may need to be addressed here?

**Comment by ngam** [comment]
Okay, I tested the second item further and it seems it was an issue on my end, one would need to actually compile `-march=x` on an `x` machine... 

I still don't know about the other item...

**Comment by xhochy** [comment]
@ngam Can you ping me on the relevant PR? I don't have enough information to give you good answers here.

**Comment by ngam** [comment]
Yes, will follow up separately on each item, e.g. https://github.com/conda-forge/tensorflow-feedstock/issues/250 for 2
